//
//  CoreDataProtocol.swift
//  CommunityApp
//
//  Created by Javon Luke on 2018-05-26.
//  Copyright © 2018 Javon Luke. All rights reserved.
//

import Foundation
import UIKit

protocol CoreDataProtocol {
    // MARK: Get function
    // func getTask(jobID: String, taskID: String) -> Task
    // func getTasks(jobID: String) -> [Task]
    func getJob(jobID: String) -> Job
    func getJobs() -> [Job]
   /*
    // MARK: Set function
    func setTaskText(taskID: String, text: String)
    func setTaskVideo(taskID: String, video: Data)
    func setTaskAudio(taskID: String, audio: Data)
    func setTaskPhoto(taskID: String, photo: UIImage)
    
    // MARK: Disable function
    func jobDisable(disable: Bool)
    func taskDisable(disable: Bool)
    func taskTextDisable(disable: Bool)
    func taskAudioDisable(disable: Bool)
    func taskVideoDisable(disable: Bool)
    func taskPhotoDisable(disable: Bool)
    
    // MARK: Create function
    func createJob() -> Job // The ID should be generated by you
    func createJob(title: String) -> Job
    func createTask(job: Job) -> Task // The ID should be generated by you
    func createTask(job: Job, title: String) -> Task
    func createTask(job: Job, title: String, text: String) -> Task
    
    // MARK: Delete function
    func deleteJob(jobID: String)
    func deleteTask(jobID: String, taskID: String)
    */
    // MARK: Testing function
    func createTestData() -> [Job]
    
    func removeTestData()
    
    
    // MARK: Save function - These are the update functions
    // func saveJob(job: Job) -> Bool
    // func saveTask(task: Task) -> Bool

}
